# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
np.__version__

'1.21.6'

In [3]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
a = np.zeros(10)
np.size(a)


10

In [ ]:
a.itemsize

8

In [ ]:
memory_size = np.size(a) * a.itemsize
memory_size

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
array = np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
list = np.arange(10,50)
list

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
list[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
a = [1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [6]:
np.random.random((3,3,3))

array([[[0.59006669, 0.42470299, 0.61943117],
        [0.78763443, 0.6641205 , 0.83579591],
        [0.86048086, 0.21385943, 0.83833343]],

       [[0.29707223, 0.68364948, 0.80925842],
        [0.62976218, 0.70438747, 0.00250784],
        [0.18894805, 0.40690312, 0.40710932]],

       [[0.44913773, 0.57338488, 0.2372235 ],
        [0.07933987, 0.94625785, 0.32016628],
        [0.32577017, 0.81648414, 0.02890977]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
arr = np.random.random((10,10))
arr

array([[0.12747372, 0.45960647, 0.70182364, 0.46816571, 0.14472851,
        0.47426829, 0.76404442, 0.22244733, 0.33282326, 0.95203829],
       [0.29472622, 0.95396353, 0.06282209, 0.36264027, 0.6172337 ,
        0.42326987, 0.3988215 , 0.85357869, 0.49116723, 0.55507735],
       [0.16131486, 0.77161491, 0.90313261, 0.26076863, 0.38005652,
        0.0803016 , 0.42180281, 0.7530724 , 0.13012078, 0.62219779],
       [0.50783101, 0.42455934, 0.10371027, 0.16732968, 0.43693798,
        0.04100449, 0.02254536, 0.74382314, 0.87196322, 0.94795577],
       [0.29033479, 0.89987259, 0.79541457, 0.56295569, 0.19607464,
        0.70852745, 0.12376838, 0.06270121, 0.86522458, 0.64255026],
       [0.45448166, 0.70952421, 0.88100183, 0.26938401, 0.24443087,
        0.2462705 , 0.6906914 , 0.30692231, 0.59844837, 0.17338402],
       [0.06497155, 0.39956955, 0.64371293, 0.38701803, 0.58614403,
        0.94419305, 0.08973594, 0.81550406, 0.18340922, 0.46749071],
       [0.50483758, 0.58385301, 0.5218879

In [ ]:
np.min(arr)

0.003135140024416949

In [ ]:
np.max(arr)

0.9539635298599999

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
l = np.random.random(30)
l

0.4825886130084681

In [ ]:
l.mean()

0.4825886130084681

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
np.pad(x,pad_width = 1, constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
np.diag([0,1,2,3,4])

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
np.unravel_index(99,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
a = np.zeros(8, dtype=int)
x = np.tile(a,(8,1))
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.random((5,5))
x = (x - x.min())/(x.max() - x.min())
x

array([[0.16912273, 0.41677042, 0.55566921, 0.84228823, 0.35470332],
       [0.85712967, 0.00941015, 0.28055352, 0.        , 0.61771037],
       [0.58629555, 0.76939193, 0.77781175, 0.12459435, 1.        ],
       [0.25682941, 0.94018196, 0.81482627, 0.82159514, 0.87362025],
       [0.59981321, 0.28104981, 0.81297623, 0.01282514, 0.6583703 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x = np.random.random((5,3))
y = np.random.random((3,2))
z = np.dot(x,y)
z

array([[1.06729364, 0.83274531],
       [1.03856453, 0.53002989],
       [1.46081326, 0.4186524 ],
       [1.54221426, 0.91104079],
       [0.8042002 , 0.36765638]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
n = (arr>2) & (arr <8)
arr[n] *= -1
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))

10


In [ ]:
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = 3
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

27
4
False
3j
3.0
False


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
s = np.random.uniform(-5,5,10)
s

array([-3.878737  ,  3.66479567,  1.22381371,  4.13722232, -2.26399221,
       -0.52767032,  1.85945069,  4.64531184,  0.94441497,  1.59303865])

In [ ]:
x = np.ceil(np.abs(s),s)
x

array([4., 4., 2., 5., 3., 1., 2., 5., 1., 2.])

In [ ]:
np.copysign(x, s)

array([4., 4., 2., 5., 3., 1., 2., 5., 1., 2.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x = np.arange(5,20)
y = np.arange(15,30)
np.intersect1d(x,y)


array([15, 16, 17, 18, 19])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
z = np.seterr(all='ignore')
np.ones(2)/0
np.seterr(**z)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [ ]:
x = np.errstate(all='ignore')
np.arange(3) / 0


array([nan, inf, inf])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
yesterday

numpy.datetime64('2022-11-04')

In [ ]:
today = np.datetime64('today', 'D')
today

numpy.datetime64('2022-11-05')

In [ ]:
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
tomorrow

numpy.datetime64('2022-11-06')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(1)*2
B = np.ones(1)*1
print(np.add(A,B,out=B))
print(np.divide(A,2,out=A))
print(np.negative(A,out=A))
print(np.multiply(A,B,out=A))

[3.]
[1.]
[-1.]
[-3.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
z = np.random.uniform(0,10,10)
print(z - z%1)
print(np.floor(z))
print(np.ceil(z))
print(z.astype(int))
print(np.trunc(z))

[7. 4. 0. 3. 7. 6. 3. 6. 0. 9.]
[7. 4. 0. 3. 7. 6. 3. 6. 0. 9.]
[ 8.  5.  1.  4.  8.  7.  4.  7.  1. 10.]
[7 4 0 3 7 6 3 6 0 9]
[7. 4. 0. 3. 7. 6. 3. 6. 0. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x = np.zeros((5,5),dtype = int)
x += np.arange(5)
x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for i in range(10):
        yield i
x = np.fromiter(generate(),dtype=int,count=-1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
np.linspace(0, 1 ,num =12, endpoint=False)[1:-1]

array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.41666667,
       0.5       , 0.58333333, 0.66666667, 0.75      , 0.83333333])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
a = np.random.random(10)
a.sort()
a

array([0.11233469, 0.13747973, 0.18983528, 0.33986533, 0.38814465,
       0.39228459, 0.4815119 , 0.55320899, 0.70400307, 0.81647208])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
z = np.arange(10)
np.add.reduce(z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
a = np.random.randint(0,2,6)
b = np.random.randint(0,2,6)
np.allclose(a,b)

False

In [ ]:
np.array_equal(a,b)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
z = np.zeros(10,dtype = int)
z.flags.writeable = False
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
z = np.random.random((10,2))
x,y = z[:,0], z[:,1]
s = np.sqrt(x**2 + y**2)
t = np.arctan2(y,x)
print(s)
print(t)

[0.57597142 0.91812518 0.91414835 0.77665484 0.79080804 1.15479144
 0.26631179 0.48751282 0.27293468 0.60619911]
[1.32543935 1.3465015  1.18079624 0.75118545 1.43008173 0.59476912
 0.88508653 0.25196818 1.10151831 1.31930287]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
z = np.random.random(10)
z[z.argmax()] = 0
z

array([0.57182295, 0.        , 0.69446803, 0.69951491, 0.28690535,
       0.5436154 , 0.51756271, 0.78732611, 0.08965341, 0.8432809 ])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
z = np.zeros((3,3), [('x',float),('y',float)])
z['x']  = np.meshgrid(np.linspace(0,1,3))
z['y'] = np.meshgrid(np.linspace(0,1,3))
z

array([[(0. , 0. ), (0.5, 0.5), (1. , 1. )],
       [(0. , 0. ), (0.5, 0.5), (1. , 1. )],
       [(0. , 0. ), (0.5, 0.5), (1. , 1. )]],
      dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x = np.random.random(5)
y = np.random.random(4)

c = 1.0/ np.subtract.outer(x,y)
c

array([[ -8.78393428, -75.50917704,  -4.53860166, 176.71087438],
       [ -2.3678914 ,  -3.10833269,  -1.89105753,  -3.30236267],
       [ -2.70602631,  -3.71823543,  -2.10069234,  -3.99932183],
       [ -6.54827527, -19.18973727,  -3.85802551, -30.11249759],
       [ -5.02284806, -10.15337125,  -3.27248462, -12.56485504]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [ ]:
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions()
x = np.zeros((4, 4))
x


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x = np.arange(100)
a = np.random.uniform(0,100)
i = (np.abs(x-a)).argmin()
x[i]

29

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
np.zeros(5, [ ('position', [ ('x', float ),('y', float)]),
              ('color',    [ ('r', float),('g', float),('b', float)])])

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
a = np.random.random((100,2))
x,y = np.atleast_2d(a[:,0],a[:,1])
v = np.sqrt((x-x.T)**2 + (y-y.T)**2)
v


array([[0.        , 0.67910455, 0.44094837, ..., 0.44676701, 0.24350392,
        0.48341988],
       [0.67910455, 0.        , 0.64902904, ..., 0.71312149, 0.69429796,
        0.60516514],
       [0.44094837, 0.64902904, 0.        , ..., 0.06610651, 0.21837075,
        0.82719697],
       ...,
       [0.44676701, 0.71312149, 0.06610651, ..., 0.        , 0.20822811,
        0.86083312],
       [0.24350392, 0.69429796, 0.21837075, ..., 0.20822811, 0.        ,
        0.69406723],
       [0.48341988, 0.60516514, 0.82719697, ..., 0.86083312, 0.69406723,
        0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [13]:
a = (np.random.rand(10)*100).astype(np.float32)
b = a.view(np.int32)
b[:] = a
b

array([25, 89, 62, 46, 77, 77, 79, 70, 46, 50], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
             ,  , 9,10,11''')
z = np.genfromtxt(s, dtype= int, delimiter=",")
z

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
a = np.arange(6).reshape(3,2)
for index, x in np.ndenumerate(a):
    print(index, x)

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5


In [ ]:
for index in np.ndindex(a.shape):
    print(index,z[index])

(0, 0) 1
(0, 1) 2
(1, 0) 6
(1, 1) -1
(2, 0) -1
(2, 1) -1


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-((d-mu)**2 / ( 2.0 * sigma**2 )))
g

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
p=4
o = np.zeros((10,10))
np.put(o,np.random.choice(range(10*10), p, replace=False),1)
print(o)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x = np.random.rand(5, 10)
z = x - x.mean(axis=1, keepdims=True)
z

array([[ 0.07908733,  0.10335352, -0.07096487, -0.05830472, -0.30408192,
        -0.5853405 ,  0.32515922,  0.11776246,  0.11588088,  0.27744861],
       [-0.05581378, -0.2750644 ,  0.3170366 ,  0.39258067,  0.29207879,
        -0.43243513,  0.2428928 , -0.46486813,  0.16360558, -0.180013  ],
       [ 0.06174499, -0.06702882,  0.29823099, -0.28025163,  0.34771249,
        -0.0862317 ,  0.35223952, -0.21408961, -0.45989557,  0.04756935],
       [ 0.46042085,  0.53924723,  0.28943356, -0.30606563, -0.24405165,
        -0.26564531,  0.27369462, -0.37526197, -0.21139681, -0.1603749 ],
       [-0.00934768, -0.28932602,  0.14663531,  0.25700182, -0.09274599,
         0.0487339 ,  0.32937528,  0.27050475, -0.01367254, -0.64715882]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
n = np.random.randint(0,10,(3,3))
n[n[:,1].argsort()]

array([[4, 2, 6],
       [7, 7, 5],
       [3, 9, 2]])

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
n = np.random.randint(0,3,(4,10))
(~n.any(axis=0)).any()


False

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
x = np.random.uniform(1, 12, 5)
v = 4
n = x.flat[np.abs(x - v).argmin()]
n

4.284516266153078

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
s = np.nditer([A,B,None])
for x,y,z in s: z[...] = x + y
print(s.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [14]:
class Array(np.ndarray):
    def __new__(cls, array, name = 'name1'):
        a = np.asarray(array).view(cls)
        a.name = name
        return a

    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(a, 'name', "name1")

x = Array(np.arange(10), "range_10")
x.name       

'range_10'

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
z = np.ones(10)
a = np.random.randint(0,len(z),20)
z += np.bincount(a, minlength=len(z))
z

array([4., 2., 3., 4., 1., 3., 3., 5., 2., 3.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
x = [2,1,4,5,6,2]
f = [1,2,3,4,5,6]
y = np.bincount(x,f)
y

array([0., 2., 7., 0., 3., 4., 5.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [18]:
w, h = 256, 256
a = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(a.reshape(-1, 3), axis=0)
n = len(colors)
n

64

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
a = np.random.randint(0,10,(3,4,3,4))
y = a.sum(axis=(-2,-1))
z = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
z

array([[60, 32, 53, 56],
       [49, 37, 51, 59],
       [82, 54, 66, 54]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
x = np.random.uniform(0,1,10)
y = np.random.randint(0,10,10)
sums = np.bincount(y, weights=x)
counts = np.bincount(y)
mean = sums / counts
mean

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


array([       nan, 0.97766047, 0.21759331, 0.89700567, 0.85808168,
       0.89253188,        nan, 0.26253904, 0.4608335 ])

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
x = np.random.uniform(0,1,(3,3))
y = np.random.uniform(0,1,(3,3))
np.diag(np.dot(x,y))

array([1.18953805, 0.62519644, 1.11404963])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
x = np.array([1,2,3,4,5])
p = 2
new_nums = np.zeros(len(x) + (len(x)-1)*(p))
new_nums[::p+1] = x
print(new_nums)

[1. 0. 0. 2. 0. 0. 3. 0. 0. 4. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
x = np.ones((5,5,3))
y = 3*np.ones((5,5))
z = x*y[:,:,None]
z

array([[[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
n = np.arange(20).reshape(5,4)
n[[0,1]] = n[[1,0]]
n

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [19]:
a = np.random.randint(0,100,(10,3))
x = np.roll(a.repeat(2,axis=1),-1,axis=1)
x = x.reshape(len(x)*3,2)
x = np.sort(x,axis=1)
y = x.view( dtype=[('p0',x.dtype),('p1',x.dtype)] )
y = np.unique(y)
y

array([( 1,  7), ( 1, 30), ( 2, 25), ( 2, 39), ( 5, 13), ( 5, 79),
       ( 7, 30), ( 9, 30), ( 9, 90), (13, 79), (14, 30), (14, 48),
       (14, 54), (14, 93), (16, 49), (16, 70), (22, 56), (22, 57),
       (25, 39), (30, 90), (30, 93), (46, 78), (46, 90), (48, 54),
       (49, 70), (54, 73), (54, 88), (56, 57), (73, 88), (78, 90)],
      dtype=[('p0', '<i8'), ('p1', '<i8')])

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
a = np.bincount([1,2,3,4,5,6])
b = np.repeat(np.arange(len(a)), a)
a

array([0, 1, 1, 1, 1, 1, 1])

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n) :
    test = np.cumsum(a, dtype=float)
    test[n:] = test[n:] - test[:-n]
    return test[n - 1:] / n
moving_average(np.arange(20),5)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [23]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
Z

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
a = np.random.randint(0,2,10)
np.logical_not(a, out=a)

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1])

In [ ]:
a = np.random.randint(0,2,10)
np.negative(a, out=a)

array([ 0, -1,  0, -1, -1, -1,  0, -1,  0, -1])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [26]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
np.array([distance(P0,P1,pi) for pi in p])

array([[3.57797684e+00, 9.50872275e+00, 5.84516132e+00, 3.04599359e+00,
        1.28412939e+01, 1.66292865e+00, 6.80990129e+00, 6.16752837e+00,
        9.00535691e+00, 9.30142551e+00],
       [6.69637147e+00, 2.86628037e+00, 5.25848422e-01, 5.08151159e+00,
        1.91558178e+00, 6.76307226e+00, 1.30455599e+00, 2.78066369e-01,
        1.38408705e+00, 1.58544986e+00],
       [5.19769348e+00, 1.38198923e+01, 8.03418669e-02, 2.11871159e+00,
        1.35012863e+01, 3.30789745e+00, 1.02937683e+01, 2.87886001e-01,
        1.27928056e+01, 1.00325184e+01],
       [5.67047682e+00, 1.37677790e+01, 1.11548647e+00, 1.03816747e+00,
        1.41204944e+01, 3.08585775e+00, 1.04255086e+01, 1.30513655e+00,
        1.28600534e+01, 1.06414750e+01],
       [2.50765039e+00, 1.78529119e+00, 9.92954617e+00, 5.71478694e+00,
        7.60315423e+00, 9.52084683e+00, 5.55663969e-01, 1.05823071e+01,
        1.48924451e+00, 3.99664499e+00],
       [1.19257965e+01, 3.49872856e+00, 2.42022483e+00, 3.32495319e+00,
   

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
from numpy.lib import stride_tricks
a = np.arange(1,15,dtype=np.uint32)
b = stride_tricks.as_strided(a,(11,4),(4,4))
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [27]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
rank

10

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
x = np.random.randint(0, 10, 40)
np.bincount(x).argmax()

1

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
arr = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (arr.shape[0]-3)
j = 1 + (arr.shape[1]-3)
z = np.lib.stride_tricks.as_strided(arr, shape=(i, j, n, n), strides = arr.strides + arr.strides)
z

array([[[[3, 1, 0],
         [0, 3, 2],
         [4, 4, 4]],

        [[1, 0, 3],
         [3, 2, 1],
         [4, 4, 4]],

        [[0, 3, 4],
         [2, 1, 2],
         [4, 4, 0]],

        [[3, 4, 3],
         [1, 2, 0],
         [4, 0, 4]],

        [[4, 3, 1],
         [2, 0, 1],
         [0, 4, 2]],

        [[3, 1, 3],
         [0, 1, 3],
         [4, 2, 2]],

        [[1, 3, 2],
         [1, 3, 4],
         [2, 2, 2]],

        [[3, 2, 3],
         [3, 4, 1],
         [2, 2, 3]]],


       [[[0, 3, 2],
         [4, 4, 4],
         [4, 4, 3]],

        [[3, 2, 1],
         [4, 4, 4],
         [4, 3, 2]],

        [[2, 1, 2],
         [4, 4, 0],
         [3, 2, 0]],

        [[1, 2, 0],
         [4, 0, 4],
         [2, 0, 0]],

        [[2, 0, 1],
         [0, 4, 2],
         [0, 0, 0]],

        [[0, 1, 3],
         [4, 2, 2],
         [0, 0, 0]],

        [[1, 3, 4],
         [2, 2, 2],
         [0, 0, 2]],

        [[3, 4, 1],
         [2, 2, 3],
         [0, 2, 2]]],


    

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [29]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [30]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [32]:
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
result

rec.array([(b'Yasemin Rayner', 88.5, 90), (b'Ayaana Mcnamara', 87. , 99),
           (b'Jody Preece', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [35]:
x = np.random.rand(int(5e7))

np.power(x,3)

array([0.11953643, 0.19481283, 0.85028303, ..., 0.37873036, 0.01204703,
       0.11281125])

In [36]:
x*x*x

array([0.11953643, 0.19481283, 0.85028303, ..., 0.37873036, 0.01204703,
       0.11281125])

In [37]:
np.einsum('i,i,i->i',x,x,x)

array([0.11953643, 0.19481283, 0.85028303, ..., 0.37873036, 0.01204703,
       0.11281125])

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [40]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
rows

array([6, 7])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [43]:
Z = np.random.randint(0,5,(10,3))
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
U

array([[2, 3, 3],
       [2, 3, 3],
       [3, 0, 0],
       [4, 1, 3],
       [2, 0, 4],
       [0, 3, 2],
       [0, 3, 3],
       [2, 4, 3],
       [1, 1, 2],
       [1, 4, 1]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [44]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [45]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
uZ

array([[0, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [46]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [47]:
X = np.random.randn(100)
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.21614256  0.10021661]
